# Pyr_suite2p_2 Notebook Guide

This notebook compares predicted firing-rate/activity traces against the real firing rate derived from voltage spikes.

Run only the analysis path you need:

1. **Suite2p baseline**: run the loader and the `standard` suite2p cell.
2. **FR-bin z-scoring**: run the `fr_bin` suite2p cell when you want error variance matched to real-FR bins.
3. **Shift-null episodes**: run the `shift_null` suite2p cell when you want window-based over/under-estimation episodes instead of direct z-threshold episodes.
4. **CASCADE**: run the CASCADE cell only when the CASCADE package/model folder is available.

Main outputs are HTML/SVG figures plus CSV tables. Per-cell outputs are written inside each cell folder under the requested `out_subdir`; pooled summary outputs are written by `pyr_suite2p_based.py` to the configured summary folder.

Important terms:

- **real FR**: firing rate estimated from voltage spike times.
- **predicted FR**: suite2p spks-derived FR or CASCADE-derived activity converted to Hz.
- **lag correction**: the predicted trace is shifted within `max_lag_s` to maximize correlation with real FR.
- **underestimation**: predicted FR is lower than real FR.
- **overestimation**: predicted FR is higher than real FR.
- **corrlation_thr**: intentionally misspelled in the function API for backward compatibility; it filters low-correlation cells from pooled stacked-bar summary plots.
- **spike PKL priority**: loading now prefers corrected high-plateau-removal spike PKLs (`spike_detection_refined_new{suffix}_rm_complex_highplateau.pkl`) when available, then falls back to older corrected/plus-plateau/raw PKLs.

## Cell 1 - Loading Examples

Template cell showing the two supported ways to create `cells`:

- `db_path`: load cell folders from a CSV table.
- `cell_paths`: manually provide specific cell folders.

Do not leave both options active unless you intentionally want the second assignment to overwrite the first.

In [1]:
from pyr_suite2p_based import load_cells_with_spike_pkls

# CELL PURPOSE: examples for loading cells.
# This cell is a template. Use either DB mode OR direct-path mode, not both.
# If both lines are left active, the second assignment overwrites the first `cells` variable.

# Option 1: load all cells listed in a CSV database.
cells = load_cells_with_spike_pkls(db_path=r"Z:\...\PyrLow.csv")

# Option 2: load specific cell folders directly.
cells = load_cells_with_spike_pkls(cell_paths=[r"Z:\...\cell12", r"Z:\...\cell37"])

FileNotFoundError: [Errno 2] No such file or directory: 'Z:\\...\\PyrLow.csv'

## Cell 2 - Quick Loader

Creates the `cells` variable used by later analysis cells. Replace the CSV path with the database you want to analyze.

In [1]:
from pyr_suite2p_based import load_cells_with_spike_pkls

# CELL PURPOSE: quick loader for the `cells` object.
# `cells` is the input list used by the suite2p and CASCADE evaluation cells below.
# The loader prefers corrected high-plateau-removal spike PKLs when available.
# Replace the CSV path if you want to analyze a different cell list.
cells = load_cells_with_spike_pkls(db_path=r"Z:\...\PyrLow.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'Z:\\...\\PyrLow.csv'

## Cell 3 - Suite2p Standard Analysis

Runs the default suite2p-spks evaluation using global error z-scoring. This is the baseline analysis and also writes a compact CSV summary.

In [11]:
from pyr_suite2p_based import (
    load_cells_with_spike_pkls,
    evaluate_suite2p_spks_as_continuous_activity,
)

# CELL PURPOSE: run the baseline suite2p-spks-vs-real-FR analysis.
# This uses the default error_z_mode="standard": one global error sigma per cell/state.
# Outputs are saved per cell under `cell_path/out_subdir` and pooled summaries under the summary folder.

# Load cells from the CSV database. You can replace this with direct cell_paths if needed.
cells = load_cells_with_spike_pkls(
    db_path=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\Dendrites\PyrLowFR.csv"
    # or: cell_paths=[r"Z:\...\cell1", r"Z:\...\cell2"]
)

res = evaluate_suite2p_spks_as_continuous_activity(
    loaded_cells=cells,
    out_subdir="suite2p_spks_eval_continuous",
    smooth_sigma_s=0.2,  # Gaussian smoothing applied to real FR and predicted FR.
    max_lag_s=0.5,       # Search +/- this lag and use the best correlation alignment.
    z_thresh=2.0,        # Standard mode flags windows where error z is above/below +/-2.
    save_svg=True,       # True requires kaleido; HTML is saved regardless by the function.
)

import os
import numpy as np

# Show the mapping between each valid result row and the subplot row in all-cells summary figures.
valid = res.loc[res["ok"] == True].copy().reset_index(drop=True)

mapping = valid[["cell_path", "state"]].copy()
mapping["subplot_row"] = np.arange(1, len(mapping) + 1)  # 1-based row index
mapping["subplot_title"] = mapping["cell_path"].map(lambda p: os.path.basename(str(p))) + " | " + mapping["state"]

display(mapping)

# Optional quick checks.
# display(res.head(20))
# print("valid rows:", int(res["ok"].fillna(False).sum()), "of", len(res))

# Save a compact CSV summary of the run.
out_csv = r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\Dendrites\suite2p_spks_eval_summary.csv"
res.to_csv(out_csv, index=False)
print("saved:", out_csv)

,cell_path,state,subplot_row,subplot_title
0,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\R\...,main,1,cell0 | main
1,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\R\...,main,2,cell1 | main
2,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\L\...,main,3,cell0 | main
3,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\l\...,main,4,cell0 | main
4,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,main,5,cell0 | main
5,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,m0,6,cell1 | m0
6,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,r0,7,cell1 | r0
7,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,m1,8,cell1 | m1
8,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,r1,9,cell1 | r1
9,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\RL...,main,10,cell4 | main
10,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\RL...,main,11,cell5 | main
11,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\RL...,main,12,cell1 | main
12,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\RL...,main,13,cell2 | main
13,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,m0,14,cell0 | m0
14,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,r0,15,cell0 | r0
15,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,m1,16,cell0 | m1
16,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,r1,17,cell0 | r1
17,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,m0,18,cell1 | m0
18,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,r0,19,cell1 | r0
19,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,m1,20,cell1 | m1
20,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,r1,21,cell1 | r1
21,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,main,22,cell1 | main
22,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,main,23,cell1 | main
23,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,main,24,cell4 | main
24,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,main,25,cell6 | main
25,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,main,26,cell1 | main
26,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,main,27,cell2 | main
27,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,main,28,cell0 | main
28,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,main,29,cell1 | main
29,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,main,30,cell2 | main
30,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,main,31,cell2 | main
31,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,main,32,cell0 | main
32,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,main,33,cell1 | main
33,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc43\17...,main,34,cell0 | main
34,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc46\R\...,main,35,cell0 | main
35,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc46\R\...,main,36,cell1 | main
36,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc46\R\...,main,37,cell3 | main
37,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc46\R\...,main,38,cell4 | main
38,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc46\RL...,main,39,cell0 | main
39,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,m0,40,cell0 | m0
40,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,r0,41,cell0 | r0
41,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,m1,42,cell0 | m1
42,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,r1,43,cell0 | r1

saved: Z:\Adam-Lab-Shared\Data\Michal_Rubin\Dendrites\suite2p_spks_eval_summary.csv

## Cell 4 - Suite2p FR-Bin Error Mode

Runs the same suite2p analysis, but computes error z-score relative to variance within matched real-FR bins: 0-5, 5-10, 10-15, 15-20, and 20+ Hz.

In [2]:
import importlib
import pyr_suite2p_based as psb
importlib.reload(psb)

from pyr_suite2p_based import (
    load_cells_with_spike_pkls,
    evaluate_suite2p_spks_as_continuous_activity,
)

# CELL PURPOSE: run suite2p analysis with FR-bin-matched error z-scoring.
# error_z_mode="fr_bin" computes z[t] = error[t] / sigma(real-FR-bin for time t).
# FR bins are 0-5, 5-10, 10-15, 15-20, and 20+ Hz.
# Use this when you want the error threshold to respect different variance at low/high FR.

cells = load_cells_with_spike_pkls(
    db_path=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\Dendrites\PyrLowFR.csv"
    # or: cell_paths=[r"Z:\...\cell1", r"Z:\...\cell2"]
)

res = evaluate_suite2p_spks_as_continuous_activity(
    loaded_cells=cells,
    out_subdir="suite2p_spks_eval_continuous",
    smooth_sigma_s=0.2,
    max_lag_s=0.5,
    z_thresh=2.0,
    error_z_mode="fr_bin",
    save_svg=True,
)

c:\Users\owner\AppData\Local\Programs\Python\Python310\lib\site-packages\kaleido\scopes\base.py:185: DeprecationWarning:

setDaemon() is deprecated, set the daemon attribute instead

## Cell 5 - Rank Complex Underestimation Cells

Reads the pooled event table from a previous analysis and ranks cells by the number/fraction of complex events that landed in underestimation windows.

In [4]:
import pandas as pd
import numpy as np
import os

# CELL PURPOSE: rank cells by complex-spike events that fall inside underestimation windows.
# Run this after an analysis cell has generated `all_cells_event_under_over_by_type_size.csv`.
# The result helps identify cells where the model misses complex-spike-related activity.

evt_csv = r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\suite2p_vs_realfr\countineous_aproch\all_cells_event_under_over_by_type_size.csv"
evt = pd.read_csv(evt_csv)

# Keep only complex-underestimation events.
sub = evt[
    (evt["category"].astype(str).str.lower() == "under") &
    (evt["event_class"].astype(str).str.lower() == "complex")
].copy()

# Rank by number of complex underestimated events.
ranked = (
    sub.groupby(["cell_path", "cell_name"], as_index=False)
       .size()
       .rename(columns={"size": "n_complex_underestimated"})
       .sort_values("n_complex_underestimated", ascending=False)
       .reset_index(drop=True)
)

# 1-based rank.
ranked["rank"] = np.arange(1, len(ranked) + 1)

# Optional context: total complex events and fraction underestimated.
total_complex = (
    evt[evt["event_class"].astype(str).str.lower() == "complex"]
    .groupby(["cell_path", "cell_name"], as_index=False)
    .size()
    .rename(columns={"size": "n_complex_total"})
)
ranked = ranked.merge(total_complex, on=["cell_path", "cell_name"], how="left")
ranked["frac_complex_underestimated"] = ranked["n_complex_underestimated"] / ranked["n_complex_total"]

ranked = ranked[["rank", "cell_name", "n_complex_underestimated", "n_complex_total", "frac_complex_underestimated", "cell_path"]]

display(ranked)

out_csv = os.path.join(os.path.dirname(evt_csv), "ranked_cells_complex_underestimation.csv")
ranked.to_csv(out_csv, index=False)
print("saved:", out_csv)

,rank,cell_name,cell_path,n_complex_underestimated,n_complex_total,frac_complex_underestimated
0,1,cell1,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,16,21,0.761905
1,2,cell1,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,14,14,1.000000
2,3,cell2,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\RL...,12,16,0.750000
3,4,cell0,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc46\RL...,12,12,1.000000
4,5,cell6,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,12,19,0.631579
5,6,cell4,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,11,12,0.916667
6,7,cell0,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,11,12,0.916667
7,8,cell1,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\R\...,10,13,0.769231
8,9,cell0,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\R\...,9,9,1.000000
9,10,cell1,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,8,9,0.888889
10,11,cell1,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc46\R\...,8,9,0.888889
11,12,cell5,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\RL...,8,12,0.666667
12,13,cell0,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,8,14,0.571429
13,14,cell0,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\L\...,7,12,0.583333
14,15,cell4,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\RL...,6,7,0.857143
15,16,cell1,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\RW...,4,6,0.666667
16,17,cell2,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,4,5,0.800000
17,18,cell4,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc46\R\...,4,4,1.000000
18,19,cell2,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,4,4,1.000000
19,20,cell2,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,3,4,0.750000
20,21,cell1,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,3,3,1.000000
21,22,cell0,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,3,3,1.000000
22,23,cell3,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc46\R\...,3,3,1.000000
23,24,cell0,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc43\17...,3,8,0.375000
24,25,cell0,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc46\R\...,3,3,1.000000
25,26,cell1,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\RL...,3,5,0.600000
26,27,cell1,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,2,2,1.000000
27,28,cell0,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC44\L\...,2,3,0.666667
28,29,cell0,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\l\...,2,2,1.000000
29,30,cell1,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,2,3,0.666667

Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\suite2p_vs_realfr\countineous_aproch\ranked_cells_complex_underestimation.csv

## Cell 6 - Negative Correlation Diagnostic

Displays cells/states where the best lag-corrected predicted FR is negatively correlated with real FR. Run after an analysis cell that produced `res`.

In [2]:
# CELL PURPOSE: diagnostic table for cells/states with negative lag-corrected correlation.
# Run this after any evaluation cell that creates `res`.
# Negative values mean the best lagged suite2p/CASCADE prediction is anti-correlated with real FR.

neg_lag = (
    res[(res["ok"] == True) & (res["best_lag_pearson_r"] < 0)]
    [["cell_path", "state", "best_lag_pearson_r", "best_lag_s"]]
    .sort_values("best_lag_pearson_r")
)

display(neg_lag)
print("count:", len(neg_lag))

NameError: name 'res' is not defined

## Cell 7 - Suite2p Shift-Null Episodes

Runs the window-based detector for over/under-estimation episodes. This is useful when you want significant episodes based on circular-shift null distributions rather than simple pointwise z-score thresholds.

In [39]:
import importlib
import pyr_suite2p_based as psb
importlib.reload(psb)

from pyr_suite2p_based import (
    load_cells_with_spike_pkls,
    evaluate_suite2p_spks_as_continuous_activity,
)

# CELL PURPOSE: run suite2p analysis with the shift-null episode detector.
# This is separate from z-thresholding:
# 1. error = predicted FR - real FR.
# 2. Test sliding-window mean error against circular-shift nulls.
# 3. Repeat at multiple window sizes.
# 4. Merge neighboring significant windows into episodes.
# 5. Keep episodes supported by at least `shift_null_min_supported_scales` window sizes.
# `corrlation_thr` filters low-correlation cells from the pooled all-cells stacked-bar plot only.

cells = load_cells_with_spike_pkls(
    db_path=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\Dendrites\PyrLowFR.csv"
    # or: cell_paths=[r"Z:\...\cell1", r"Z:\...\cell2"]
)

res = evaluate_suite2p_spks_as_continuous_activity(
    loaded_cells=cells,
    out_subdir="suite2p_spks_eval_continuous",
    smooth_sigma_s=0.2,
    max_lag_s=0.5,
    z_thresh=2.0,  # Still used by non-shift-null plots/metadata; shift-null windows use null p-values.
    error_z_mode="shift_null",
    shift_null_window_sizes_s=(0.1,),
    shift_null_n_shifts=200,
    shift_null_min_supported_scales=1,
    shift_null_min_valid_frac=0.80,
    shift_null_merge_gap_s=0.0,
    shift_null_seed=0,
    corrlation_thr=-1.0,
    save_svg=True,
)

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

## Cell 8 - CASCADE Prediction Analysis

Uses CASCADE instead of suite2p spks as the predicted activity source, then runs the same comparison and plotting workflow. Requires the CASCADE package and the selected pretrained model folder.

In [41]:
import importlib, pyr_suite2p_based as psb
importlib.reload(psb)

# CELL PURPOSE: run the CASCADE-based activity prediction analysis.
# This is a separate prediction source from suite2p spks.
# CASCADE predicts activity from calcium; the evaluator then compares predicted FR to real FR
# using the same lag-correction, correlation, plotting, and under/over-window logic.

cells = psb.load_cells_with_spike_pkls(
    db_path=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\Dendrites\PyrLowFR.csv"
)

res_cas = psb.evaluate_cascade_as_continuous_activity(
    loaded_cells=cells,
    cascade_model_name="GC8_EXC_30Hz_smoothing50ms_high_noise",
    cascade_model_folder=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\Pretrained_models",
    smooth_sigma_s=0.2,
    max_lag_s=0.5,
    z_thresh=2.0,
    
    #error_z_mode="standard",  # Can also be "fr_bin" or "shift_null".
    error_z_mode="shift_null",
    shift_null_window_sizes_s=(0.1,),
    shift_null_n_shifts=200,
    shift_null_min_supported_scales=1,
    shift_null_min_valid_frac=0.80,
    shift_null_merge_gap_s=0.0,
    shift_null_seed=0,
    corrlation_thr=-1.0,  # Filters low-correlation cells from pooled summary plots.
    save_svg=True,
)

WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA38B6040> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:8 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA2C05310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9F981CA0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
WARNING:tensorflow:5 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D94047EE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9522FD30> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 12 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA5E1CAF0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:7 out of the last 13 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D94047AF0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:8 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D94478700> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:8 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA29774C0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:9 out of the last 12 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA2977AF0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:10 out of the last 13 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D952A18B0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D93874670> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D93874280> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D95B7E9D0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA33D2790> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA33D2550> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D93874550> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9442E1F0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:10 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D939D4D30> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:9 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9538F550> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:8 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D938A9310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:7 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D952640D0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D95264160> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA35F4430> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
WARNING:tensorflow:5 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D96FC6040> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\pyr_suite2p_based.py:1290: RuntimeWarning:

Mean of empty slice

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1664: RuntimeWarning:

Degrees of freedom <= 0 for slice.

## Cell 9 - Model Compare Bias Metrics

Runs the CASCADE-paper-style comparison requested here. It uses voltage-defined complex/plateau events from the loaded corrected PKLs, extracts peri-event calcium/true-FR/inferred-FR traces, computes temporal bias, and computes per-cell relative error/bias for suite2p and CASCADE.

Outputs:

- Per-cell/state temporal-bias plots in each `cell_path/model_compare` folder.
- Summary CSV and violin/beeswarm figure in the `model_compare` summary folder.

In [59]:
import importlib, pyr_suite2p_based as psb
importlib.reload(psb)

# Load cells again after reload so the corrected high-plateau PKLs are selected.
cells = psb.load_cells_with_spike_pkls(
    db_path=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\Dendrites\PyrLowFR.csv"
)

bias_metrics = psb.compare_suite2p_and_cascade_bias_metrics(
    loaded_cells=cells,
    summary_out_dir=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\model_compare",
    include_suite2p=True,
    include_cascade=True,
    cascade_model_name="GC8_EXC_30Hz_smoothing50ms_high_noise",
    cascade_model_folder=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\Pretrained_models",
    cascade_convert_to_hz=True,  # CASCADE output interpreted as spikes/bin then converted to instantaneous Hz
    smooth_sigma_s=0.05,       # matches the 50 ms smoothing in this CASCADE model name
    max_lag_s=0.5,
    
    scale_pred_to_true=False,  # global default (explicit per-model flags below)
    scale_pred_to_true_suite2p=True,  # scales suite2p-predicted FR to match total true spikes in each peri-alignment window
    scale_pred_to_true_cascade=False,
    use_lag_correction=True,
    peri_window_s=(-1.0, 1.0),
    align_to="vm_peak",   # use "vm_peak" to align to voltage peak instead
    save_svg=True,
)

display(bias_metrics)
print("summary CSV:", bias_metrics.attrs.get("summary_csv"))
print("summary HTML:", bias_metrics.attrs.get("summary_html"))

WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D93A348B0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:8 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9424E820> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9424E670> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
WARNING:tensorflow:5 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D93CE99D0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D93CE9310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 12 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D93CE9040> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:7 out of the last 13 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D93C9F700> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:8 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA2FC13A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:8 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA2FC11F0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:9 out of the last 12 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA366D820> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:10 out of the last 13 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DCD442B80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA24D69D0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA24D6F70> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA38B6700> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9597B4C0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA38B6310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA32D5550> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D93999670> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:10 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA75F19D0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:9 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9F981310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:8 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA282C310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:7 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D8D0ABE50> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA75F1280> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA2F52160> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
WARNING:tensorflow:5 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA347AEE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

,model,cell_path,cell_name,state,pkl_path,ok,reason,model_display,calibration_mode,pearson_corr_true_vs_pred,...,max_lag_s,lag_s,best_lag_corr,scale_pred_to_true,scale_pred_to_true_suite2p,scale_pred_to_true_cascade,scale,offset,figure_html,figure_svg
0,suite2p,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\R\...,cell0,main,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\R\...,True,,suite2p_scaled,scaled,0.711119,...,0.5,0.066667,0.711119,True,True,False,1.0,-4.440892e-16,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\R\...,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\R\...
1,suite2p,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\R\...,cell1,main,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\R\...,True,,suite2p_scaled,scaled,0.735472,...,0.5,0.066667,0.735472,True,True,False,1.0,3.552714e-15,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\R\...,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\R\...
2,suite2p,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\L\...,cell0,main,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\L\...,True,,suite2p_scaled,scaled,0.800846,...,0.5,0.066667,0.800846,True,True,False,1.0,-8.881784e-16,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\L\...,Z:\Adam-Lab-Shared\Data\Michal_Rubin\RUGC40\L\...
3,suite2p,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\l\...,cell0,main,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\l\...,True,,suite2p_scaled,scaled,0.665307,...,0.5,0.066667,0.665307,True,True,False,1.0,3.552714e-15,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\l\...,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc41\l\...
4,suite2p,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,cell0,main,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,True,,suite2p_scaled,scaled,0.736640,...,0.5,0.066667,0.736640,True,True,False,1.0,1.776357e-15,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,cascade,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,cell0,m0,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,True,,cascade_unscaled,unscaled,0.438875,...,0.5,0.000000,0.438875,False,True,False,1.0,0.000000e+00,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...
88,cascade,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,cell0,r0,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,True,,cascade_unscaled,unscaled,0.645182,...,0.5,0.033367,0.645182,False,True,False,1.0,0.000000e+00,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...
89,cascade,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,cell0,m1,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,True,,cascade_unscaled,unscaled,0.366322,...,0.5,0.066733,0.366322,False,True,False,1.0,0.000000e+00,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...
90,cascade,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,cell0,r1,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,True,,cascade_unscaled,unscaled,0.486936,...,0.5,0.100100,0.486936,False,True,False,1.0,0.000000e+00,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...
91,cascade,Z:\Adam-Lab-Shared\Data\Michal_Rubin\rugc42\Wh...,cell0,m2,None,False,Missing spike_pkl_data,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

summary CSV: Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\model_compare\model_compare\bias_metrics_model_compare.csv
summary HTML: Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\model_compare\model_compare\bias_metrics_model_compare.html

In [50]:
res_cmp = psb.compare_suite2p_and_cascade_bias_metrics(
    loaded_cells=cells,
    summary_out_dir=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\model_compare",
    include_suite2p=True,
    include_cascade=True,
    report_scaled_and_unscaled=False,
    scale_pred_to_true_suite2p=True,
    scale_pred_to_true_cascade=False,
    save_svg=True,
)

WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9F2A70D0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:8 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D943A3670> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA287B3A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
WARNING:tensorflow:5 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA4C95AF0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DAB5738B0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 12 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D996768B0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:7 out of the last 13 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DCD9D8550> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:8 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA2F770D0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:8 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9372C040> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:9 out of the last 12 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9372CDC0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:10 out of the last 13 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9F8F0B80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA60BF940> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA60BFEE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D93FECCA0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D93FEC700> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA4ED3940> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA29C3700> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9F2EE430> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:10 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA79F21F0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:9 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA79F2EE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:8 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA71B4D30> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:7 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9F2EEEE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D94263940> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA3667700> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
WARNING:tensorflow:5 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA27C24C0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

In [49]:
# NEW_CELL: CASCADE_INPUT_DIAGNOSTICS
# Purpose: debug why unscaled CASCADE output can be off by checking per-cell input properties.

import importlib
import pyr_suite2p_based as psb
importlib.reload(psb)

cells = psb.load_cells_with_spike_pkls(
    db_path=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\Dendrites\PyrLowFR.csv"
)

diag_df = psb.diagnose_cascade_input_quality(
    loaded_cells=cells,
    summary_out_dir=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\cascade_vs_realfr\countineous_aproch",
    cascade_model_name="GC8_EXC_30Hz_smoothing50ms_high_noise",
    pre_window_s=0.25,
    post_window_s=1.0,
    baseline_window_s=(-0.20, -0.05),
    peak_window_s=(0.00, 0.50),
    min_single_spike_events=5,
    save_svg=True,
)

print("rows:", len(diag_df))
print("csv:", diag_df.attrs.get("summary_csv"))
print("html:", diag_df.attrs.get("summary_html"))
print("svg:", diag_df.attrs.get("summary_svg"))

KeyboardInterrupt:

In [48]:
# NEW_CELL: CASCADE_INPUT_DIAGNOSTICS_ORIGINAL_DS
# Purpose: run the same diagnostics on the original CASCADE training datasets (DS30/31/32).

import importlib
import pyr_suite2p_based as psb
importlib.reload(psb)

cas_df = psb.diagnose_cascade_training_dataset_input_quality(
    summary_out_dir=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\cascade_vs_realfr\countineous_aproch",
    cascade_repo_root=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\_cascade_ref_repo",
    dataset_names=("DS30-GCaMP8f-m-V1", "DS31-GCaMP8m-m-V1", "DS32-GCaMP8s-m-V1"),
    cascade_model_name="GC8_EXC_30Hz_smoothing50ms_high_noise",
    isi_ms=30.0,
    pre_window_s=0.25,
    post_window_s=1.0,
    baseline_window_s=(-0.20, -0.05),
    peak_window_s=(0.00, 0.50),
    min_single_spike_events=5,
    save_svg=True,
)

print("rows:", len(cas_df))
print("csv:", cas_df.attrs.get("summary_csv"))
print("html:", cas_df.attrs.get("summary_html"))
print("svg:", cas_df.attrs.get("summary_svg"))

c:\Users\owner\anaconda3\envs\Cascade38\lib\site-packages\numpy\lib\nanfunctions.py:1113: RuntimeWarning:

All-NaN slice encountered

rows: 515
csv: Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\cascade_vs_realfr\countineous_aproch\cascade_input_diagnostics\cascade_input_diagnostics_summary_casDS.csv
html: Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\cascade_vs_realfr\countineous_aproch\cascade_input_diagnostics\cascade_input_diagnostics_summary_casDS.html
svg: Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\cascade_vs_realfr\countineous_aproch\cascade_input_diagnostics\cascade_input_diagnostics_summary_casDS.svg

In [54]:
# NEW_CELL: CASCADE_DIAG_COMPARE_TO_GT
# Compare your CASCADE input diagnostics vs original CASCADE ground-truth diagnostics.
# Saves: similarity table CSV/TSV + per-feature overlay histograms (SVG/PNG).

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import ks_2samp, wasserstein_distance

base_dir = r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\cascade_vs_realfr\countineous_aproch\cascade_input_diagnostics"
your_csv = os.path.join(base_dir, "cascade_input_diagnostics_summary.csv")
gt_csv = os.path.join(base_dir, "cascade_input_diagnostics_summary_casDS.csv")

# Optional: restrict GT to a specific dataset, e.g. DS31-GCaMP8m-m-V1
GT_DATASET_FILTER = "DS31-GCaMP8m-m-V1"

out_table_csv = os.path.join(base_dir, "cascade_input_diagnostics_similarity_table.csv")
out_table_tsv = os.path.join(base_dir, "cascade_input_diagnostics_similarity_table.tsv")
out_fig_dir = os.path.join(base_dir, "similarity_plots")
os.makedirs(out_fig_dir, exist_ok=True)

your_diag = pd.read_csv(your_csv)
gt_diag = pd.read_csv(gt_csv)
if GT_DATASET_FILTER is not None and "dataset_name" in gt_diag.columns:
    gt_diag = gt_diag[gt_diag["dataset_name"].astype(str) == str(GT_DATASET_FILTER)].copy()

# Unified feature names
for df in (your_diag, gt_diag):
    df["single_spike_amp"] = pd.to_numeric(df.get("single_spike_amp_median_dff", np.nan), errors="coerce")
    df["noise_sigma"] = pd.to_numeric(df.get("noise_sigma_dff", np.nan), errors="coerce")
    df["rise_time"] = pd.to_numeric(df.get("single_spike_rise_time_s", np.nan), errors="coerce")
    df["decay_time"] = pd.to_numeric(df.get("single_spike_decay_time_s", np.nan), errors="coerce")
    amp = pd.to_numeric(df.get("single_spike_amp", np.nan), errors="coerce")
    noi = pd.to_numeric(df.get("noise_sigma", np.nan), errors="coerce")
    with np.errstate(divide="ignore", invalid="ignore"):
        snr = amp / noi
    snr[~np.isfinite(snr)] = np.nan
    df["single_spike_snr"] = snr
    df["median_dff"] = pd.to_numeric(df.get("median_dff", np.nan), errors="coerce")

features = [
    "median_dff",
    "single_spike_amp",
    "noise_sigma",
    "single_spike_snr",
    "rise_time",
    "decay_time",
]

summary = []
for f in features:
    a = pd.to_numeric(your_diag.get(f, np.nan), errors="coerce").dropna().to_numpy(float)
    b = pd.to_numeric(gt_diag.get(f, np.nan), errors="coerce").dropna().to_numpy(float)

    if a.size < 2 or b.size < 2:
        summary.append({
            "feature": f,
            "your_n": int(a.size),
            "gt_n": int(b.size),
            "your_median": np.nan if a.size == 0 else float(np.nanmedian(a)),
            "gt_median": np.nan if b.size == 0 else float(np.nanmedian(b)),
            "your_iqr": np.nan if a.size == 0 else float(np.nanpercentile(a, 75) - np.nanpercentile(a, 25)),
            "gt_iqr": np.nan if b.size == 0 else float(np.nanpercentile(b, 75) - np.nanpercentile(b, 25)),
            "median_ratio_your_over_gt": np.nan,
            "ks_stat": np.nan,
            "ks_p": np.nan,
            "wasserstein": np.nan,
        })
        continue

    ks = ks_2samp(a, b)
    wd = wasserstein_distance(a, b)
    med_a = float(np.nanmedian(a))
    med_b = float(np.nanmedian(b))
    ratio = np.nan
    if np.isfinite(med_b) and abs(med_b) > 1e-12:
        ratio = med_a / med_b

    summary.append({
        "feature": f,
        "your_n": int(a.size),
        "gt_n": int(b.size),
        "your_median": med_a,
        "gt_median": med_b,
        "your_iqr": float(np.nanpercentile(a, 75) - np.nanpercentile(a, 25)),
        "gt_iqr": float(np.nanpercentile(b, 75) - np.nanpercentile(b, 25)),
        "median_ratio_your_over_gt": ratio,
        "ks_stat": float(ks.statistic),
        "ks_p": float(ks.pvalue),
        "wasserstein": float(wd),
    })

similarity_table = pd.DataFrame(summary)
similarity_table.to_csv(out_table_csv, index=False)
similarity_table.to_csv(out_table_tsv, sep="	", index=False)
print(similarity_table)
print("saved:", out_table_csv)
print("saved:", out_table_tsv)

# Per-feature overlay histograms
for f in features:
    a = pd.to_numeric(your_diag.get(f, np.nan), errors="coerce").dropna().to_numpy(float)
    b = pd.to_numeric(gt_diag.get(f, np.nan), errors="coerce").dropna().to_numpy(float)
    if a.size == 0 and b.size == 0:
        continue

    plt.figure(figsize=(6.0, 4.2))
    if b.size > 0:
        gt_label = "CASCADE GT (DS30/31/32)" if GT_DATASET_FILTER is None else f"CASCADE GT ({GT_DATASET_FILTER})"
        plt.hist(b, bins=20, alpha=0.5, density=True, label=gt_label, color="tab:blue")
    if a.size > 0:
        plt.hist(a, bins=20, alpha=0.5, density=True, label="Your data", color="tab:orange")
    plt.xlabel(f)
    plt.ylabel("density")
    plt.legend()
    plt.title(f"Your data vs CASCADE training data: {f}")
    plt.tight_layout()

    fig_svg = os.path.join(out_fig_dir, f"cascade_diag_compare_{f}.svg")
    fig_png = os.path.join(out_fig_dir, f"cascade_diag_compare_{f}.png")
    plt.savefig(fig_svg, dpi=300)
    plt.savefig(fig_png, dpi=300)
    plt.close()

print("saved plots in:", out_fig_dir)

            feature  your_n  gt_n  your_median  gt_median  your_iqr    gt_iqr  \
0        median_dff      43   191     0.281750   0.137049  0.218590  0.070917
1  single_spike_amp      43   191     0.317722   0.858618  0.252380  0.368558
2       noise_sigma      43   191     0.150441   0.127476  0.051366  0.060076
3  single_spike_snr      43   191     2.089795   6.286498  0.884216  2.035372
4         rise_time      38   186     0.400184   0.090200  0.482750  0.041000
5        decay_time      26   185     0.083367   0.172200  0.133425  0.131200

   median_ratio_your_over_gt   ks_stat          ks_p  wasserstein
0                   2.055829  0.690004  2.220446e-16     0.252075
1                   0.370038  0.696457  2.220446e-16     0.528587
2                   1.180145  0.267137  1.051798e-02     0.019302
3                   0.332426  0.862779  2.220446e-16     4.258603
4                   4.436624  0.657329  1.304512e-13     0.270811
5                   0.484127  0.451351  9.468224e-05     0.080483
saved: Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\cascade_vs_realfr\countineous_aproch\cascade_input_diagnostics\cascade_input_diagnostics_similarity_table.csv
saved: Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\cascade_vs_realfr\countineous_aproch\cascade_input_diagnostics\cascade_input_diagnostics_similarity_table.tsv
saved plots in: Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\cascade_vs_realfr\countineous_aproch\cascade_input_diagnostics\similarity_plots

In [61]:
# NEW_CELL: ISOLATED_EVENT_INFERRED_SPIKE_DISTRIBUTIONS
# Purpose:
#   Build CASCADE-paper-style KDE distributions of inferred spike counts,
#   but using your isolated-event selection rules from pyr_event_cal3 (event_distance),
#   and splitting by true event spike count bins: 1,2,3,4,5,6+.
#
# Figure layout:
#   rows = model (suite2p, cascade)
#   cols = event type (simple, complex, plateau)
#   each line = true spike-count bin (1..6+), with event-type color shades
#   (simple=black shades, complex=red shades, plateau=purple shades).

import importlib
import pyr_suite2p_based as psb
importlib.reload(psb)

cells = psb.load_cells_with_spike_pkls(
    db_path=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\Dendrites\PyrLowFR.csv"
)

iso_df = psb.plot_isolated_event_inferred_spike_distributions(
    loaded_cells=cells,
    summary_out_dir=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\data summery\2026\Pyr\model_compare",
    include_suite2p=True,
    include_cascade=True,
    cascade_model_name="GC8_EXC_30Hz_smoothing50ms_high_noise",
    cascade_model_folder=r"Z:\Adam-Lab-Shared\Data\Michal_Rubin\code\cal_vol_soma\Pretrained_models",
    cascade_convert_to_hz=True,
    smooth_sigma_s=0.05,
    max_lag_s=0.5,
    scale_pred_to_true=False,
    scale_pred_to_true_suite2p=True,
    scale_pred_to_true_cascade=False,
    use_lag_correction=True,
    use_cal_mask=False,
    selection_mode="event_distance",
    min_events_per_curve=6,
    kde_points=450,
    save_svg=True,
)

print("rows:", len(iso_df))
print("csv:", iso_df.attrs.get("summary_csv"))
print("html:", iso_df.attrs.get("summary_html"))
print("svg:", iso_df.attrs.get("summary_svg"))

WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9F2A7DC0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:8 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D94462C10> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D9424E8B0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
WARNING:tensorflow:5 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA52B3EE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA794B4C0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 12 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D8F0DD160> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:7 out of the last 13 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA5994160> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:8 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA5994700> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:8 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA272F430> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:9 out of the last 12 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA77871F0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:10 out of the last 13 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA7787EE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA272F310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA783FB80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D8EE28940> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D8EE28EE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA5C14D30> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA590EAF0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA590E310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:10 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA344ED30> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:9 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA5DD9550> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:8 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA5DD9DC0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:7 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020DA590EE50> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D95974940> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D95974DC0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
Spike rate inference done.
WARNING:tensorflow:5 out of the last 14 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020D93C9FEE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.